xyf:
  constants:
    document-root: root
    static-images: pic

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jooq:
      sql-dialect: mysql_8_0
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","file://${user.dir}/${xyf.constants.document-root}/"]

server:
  port: 9734
  undertow:
      accesslog:
        dir: logs
        enabled: true