xyf:
  constants:
    document-root:
    static-images: pic

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jooq:
      sql-dialect: mysql_8_0

server:
  port: 8080