xyf:
  constants:
    document-root: root

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jooq:
      sql-dialect: mysql_8_0

server:
  port: 9734
  undertow:
      accesslog:
        dir: logs
        enabled: true