/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.ChannelInfo;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelInfoRecord extends UpdatableRecordImpl<ChannelInfoRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1133037115;

    /**
     * Setter for <code>xyf.channel_info.channel_id</code>.
     */
    public void setChannelId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.channel_info.channel_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getChannelId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xyf.channel_info.channel_name</code>.
     */
    public void setChannelName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.channel_info.channel_name</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getChannelName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ChannelInfo.CHANNEL_INFO.CHANNEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ChannelInfo.CHANNEL_INFO.CHANNEL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getChannelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getChannelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getChannelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getChannelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelInfoRecord value1(String value) {
        setChannelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelInfoRecord value2(String value) {
        setChannelName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelInfoRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelInfoRecord
     */
    public ChannelInfoRecord() {
        super(ChannelInfo.CHANNEL_INFO);
    }

    /**
     * Create a detached, initialised ChannelInfoRecord
     */
    public ChannelInfoRecord(String channelId, String channelName) {
        super(ChannelInfo.CHANNEL_INFO);

        set(0, channelId);
        set(1, channelName);
    }
}
