/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.Classify;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassifyRecord extends UpdatableRecordImpl<ClassifyRecord> implements Record3<Integer, String, Byte> {

    private static final long serialVersionUID = 732105721;

    /**
     * Setter for <code>xyf.classify.classify_id</code>.
     */
    public void setClassifyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.classify.classify_id</code>.
     */
    public Integer getClassifyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xyf.classify.classify_name</code>.
     */
    public void setClassifyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.classify.classify_name</code>.
     */
    @NotNull
    @Size(max = 30)
    public String getClassifyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xyf.classify.classify_is_del</code>.
     */
    public void setClassifyIsDel(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>xyf.classify.classify_is_del</code>.
     */
    public Byte getClassifyIsDel() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Classify.CLASSIFY.CLASSIFY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Classify.CLASSIFY.CLASSIFY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Classify.CLASSIFY.CLASSIFY_IS_DEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClassifyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getClassifyIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassifyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getClassifyIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord value1(Integer value) {
        setClassifyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord value2(String value) {
        setClassifyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord value3(Byte value) {
        setClassifyIsDel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord values(Integer value1, String value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassifyRecord
     */
    public ClassifyRecord() {
        super(Classify.CLASSIFY);
    }

    /**
     * Create a detached, initialised ClassifyRecord
     */
    public ClassifyRecord(Integer classifyId, String classifyName, Byte classifyIsDel) {
        super(Classify.CLASSIFY);

        set(0, classifyId);
        set(1, classifyName);
        set(2, classifyIsDel);
    }
}
