/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.Classify;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassifyRecord extends UpdatableRecordImpl<ClassifyRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -229784508;

    /**
     * Setter for <code>xyf.classify.classify_id</code>.
     */
    public void setClassifyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.classify.classify_id</code>.
     */
    public Integer getClassifyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xyf.classify.classify_name</code>.
     */
    public void setClassifyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.classify.classify_name</code>.
     */
    @NotNull
    @Size(max = 30)
    public String getClassifyName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Classify.CLASSIFY.CLASSIFY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Classify.CLASSIFY.CLASSIFY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClassifyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassifyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord value1(Integer value) {
        setClassifyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord value2(String value) {
        setClassifyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassifyRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassifyRecord
     */
    public ClassifyRecord() {
        super(Classify.CLASSIFY);
    }

    /**
     * Create a detached, initialised ClassifyRecord
     */
    public ClassifyRecord(Integer classifyId, String classifyName) {
        super(Classify.CLASSIFY);

        set(0, classifyId);
        set(1, classifyName);
    }
}
