/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.Feedback;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeedbackRecord extends UpdatableRecordImpl<FeedbackRecord> implements Record6<Integer, String, String, String, Byte, String> {

    private static final long serialVersionUID = -1625573466;

    /**
     * Setter for <code>xyf.feedback.feedback_id</code>.
     */
    public void setFeedbackId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.feedback.feedback_id</code>.
     */
    public Integer getFeedbackId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xyf.feedback.customer_name</code>.
     */
    public void setCustomerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.feedback.customer_name</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getCustomerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xyf.feedback.customer_contact</code>.
     */
    public void setCustomerContact(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xyf.feedback.customer_contact</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getCustomerContact() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xyf.feedback.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xyf.feedback.content</code>.
     */
    @NotNull
    @Size(max = 500)
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xyf.feedback.is_deal</code>.
     */
    public void setIsDeal(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>xyf.feedback.is_deal</code>.
     */
    public Byte getIsDeal() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>xyf.feedback.remark</code>.
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xyf.feedback.remark</code>.
     */
    @Size(max = 200)
    public String getRemark() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Byte, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Byte, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Feedback.FEEDBACK.FEEDBACK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Feedback.FEEDBACK.CUSTOMER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Feedback.FEEDBACK.CUSTOMER_CONTACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Feedback.FEEDBACK.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Feedback.FEEDBACK.IS_DEAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Feedback.FEEDBACK.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFeedbackId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCustomerContact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIsDeal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFeedbackId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCustomerContact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsDeal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value1(Integer value) {
        setFeedbackId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value2(String value) {
        setCustomerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value3(String value) {
        setCustomerContact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value5(Byte value) {
        setIsDeal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord values(Integer value1, String value2, String value3, String value4, Byte value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackRecord
     */
    public FeedbackRecord() {
        super(Feedback.FEEDBACK);
    }

    /**
     * Create a detached, initialised FeedbackRecord
     */
    public FeedbackRecord(Integer feedbackId, String customerName, String customerContact, String content, Byte isDeal, String remark) {
        super(Feedback.FEEDBACK);

        set(0, feedbackId);
        set(1, customerName);
        set(2, customerContact);
        set(3, content);
        set(4, isDeal);
        set(5, remark);
    }
}
