/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.Goods;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsRecord extends UpdatableRecordImpl<GoodsRecord> implements Record9<String, String, Double, String, Integer, Byte, Integer, Integer, Integer> {

    private static final long serialVersionUID = -991379385;

    /**
     * Setter for <code>xyf.goods.goods_id</code>.
     */
    public void setGoodsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getGoodsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xyf.goods.goods_name</code>.
     */
    public void setGoodsName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_name</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getGoodsName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xyf.goods.goods_price</code>.
     */
    public void setGoodsPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_price</code>.
     */
    public Double getGoodsPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>xyf.goods.goods_brief</code>.
     */
    public void setGoodsBrief(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_brief</code>.
     */
    @Size(max = 200)
    public String getGoodsBrief() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xyf.goods.goods_recommend</code>.
     */
    public void setGoodsRecommend(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_recommend</code>.
     */
    public Integer getGoodsRecommend() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>xyf.goods.is_stick</code>.
     */
    public void setIsStick(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>xyf.goods.is_stick</code>.
     */
    public Byte getIsStick() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>xyf.goods.stick_serial</code>.
     */
    public void setStickSerial(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>xyf.goods.stick_serial</code>.
     */
    public Integer getStickSerial() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>xyf.goods.goods_serial</code>.
     */
    public void setGoodsSerial(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_serial</code>.
     */
    public Integer getGoodsSerial() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>xyf.goods.classify_id</code>.
     */
    public void setClassifyId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>xyf.goods.classify_id</code>.
     */
    @NotNull
    public Integer getClassifyId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Double, String, Integer, Byte, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Double, String, Integer, Byte, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Goods.GOODS.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Goods.GOODS.GOODS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Goods.GOODS.GOODS_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Goods.GOODS.GOODS_BRIEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Goods.GOODS.GOODS_RECOMMEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Goods.GOODS.IS_STICK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Goods.GOODS.STICK_SERIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Goods.GOODS.GOODS_SERIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Goods.GOODS.CLASSIFY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGoodsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getGoodsPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getGoodsBrief();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGoodsRecommend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIsStick();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getStickSerial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGoodsSerial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGoodsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getGoodsPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGoodsBrief();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGoodsRecommend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsStick();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStickSerial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGoodsSerial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value1(String value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value2(String value) {
        setGoodsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value3(Double value) {
        setGoodsPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value4(String value) {
        setGoodsBrief(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value5(Integer value) {
        setGoodsRecommend(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value6(Byte value) {
        setIsStick(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value7(Integer value) {
        setStickSerial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value8(Integer value) {
        setGoodsSerial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value9(Integer value) {
        setClassifyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord values(String value1, String value2, Double value3, String value4, Integer value5, Byte value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsRecord
     */
    public GoodsRecord() {
        super(Goods.GOODS);
    }

    /**
     * Create a detached, initialised GoodsRecord
     */
    public GoodsRecord(String goodsId, String goodsName, Double goodsPrice, String goodsBrief, Integer goodsRecommend, Byte isStick, Integer stickSerial, Integer goodsSerial, Integer classifyId) {
        super(Goods.GOODS);

        set(0, goodsId);
        set(1, goodsName);
        set(2, goodsPrice);
        set(3, goodsBrief);
        set(4, goodsRecommend);
        set(5, isStick);
        set(6, stickSerial);
        set(7, goodsSerial);
        set(8, classifyId);
    }
}
