/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.Goods;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsRecord extends UpdatableRecordImpl<GoodsRecord> implements Record10<String, String, Double, String, Integer, Integer, Byte, Integer, Byte, Integer> {

    private static final long serialVersionUID = -1677264854;

    /**
     * Setter for <code>xyf.goods.goods_id</code>.
     */
    public void setGoodsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getGoodsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xyf.goods.goods_name</code>.
     */
    public void setGoodsName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_name</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getGoodsName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xyf.goods.goods_price</code>.
     */
    public void setGoodsPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_price</code>.
     */
    public Double getGoodsPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>xyf.goods.goods_brief</code>.
     */
    public void setGoodsBrief(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_brief</code>.
     */
    @Size(max = 200)
    public String getGoodsBrief() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xyf.goods.goods_recommend</code>.
     */
    public void setGoodsRecommend(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_recommend</code>.
     */
    public Integer getGoodsRecommend() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>xyf.goods.goods_serial</code>.
     */
    public void setGoodsSerial(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_serial</code>.
     */
    public Integer getGoodsSerial() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>xyf.goods.goods_is_del</code>.
     */
    public void setGoodsIsDel(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_is_del</code>.
     */
    public Byte getGoodsIsDel() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>xyf.goods.goods_item</code>.
     */
    public void setGoodsItem(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_item</code>.
     */
    public Integer getGoodsItem() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>xyf.goods.goods_is_stick</code>.
     */
    public void setGoodsIsStick(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>xyf.goods.goods_is_stick</code>.
     */
    public Byte getGoodsIsStick() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>xyf.goods.classify_id</code>.
     */
    public void setClassifyId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>xyf.goods.classify_id</code>.
     */
    @NotNull
    public Integer getClassifyId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Double, String, Integer, Integer, Byte, Integer, Byte, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Double, String, Integer, Integer, Byte, Integer, Byte, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Goods.GOODS.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Goods.GOODS.GOODS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Goods.GOODS.GOODS_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Goods.GOODS.GOODS_BRIEF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Goods.GOODS.GOODS_RECOMMEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Goods.GOODS.GOODS_SERIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Goods.GOODS.GOODS_IS_DEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Goods.GOODS.GOODS_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Goods.GOODS.GOODS_IS_STICK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Goods.GOODS.CLASSIFY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGoodsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getGoodsPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getGoodsBrief();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGoodsRecommend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGoodsSerial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getGoodsIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGoodsItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getGoodsIsStick();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGoodsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getGoodsPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGoodsBrief();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGoodsRecommend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGoodsSerial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getGoodsIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGoodsItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getGoodsIsStick();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getClassifyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value1(String value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value2(String value) {
        setGoodsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value3(Double value) {
        setGoodsPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value4(String value) {
        setGoodsBrief(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value5(Integer value) {
        setGoodsRecommend(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value6(Integer value) {
        setGoodsSerial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value7(Byte value) {
        setGoodsIsDel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value8(Integer value) {
        setGoodsItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value9(Byte value) {
        setGoodsIsStick(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord value10(Integer value) {
        setClassifyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoodsRecord values(String value1, String value2, Double value3, String value4, Integer value5, Integer value6, Byte value7, Integer value8, Byte value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsRecord
     */
    public GoodsRecord() {
        super(Goods.GOODS);
    }

    /**
     * Create a detached, initialised GoodsRecord
     */
    public GoodsRecord(String goodsId, String goodsName, Double goodsPrice, String goodsBrief, Integer goodsRecommend, Integer goodsSerial, Byte goodsIsDel, Integer goodsItem, Byte goodsIsStick, Integer classifyId) {
        super(Goods.GOODS);

        set(0, goodsId);
        set(1, goodsName);
        set(2, goodsPrice);
        set(3, goodsBrief);
        set(4, goodsRecommend);
        set(5, goodsSerial);
        set(6, goodsIsDel);
        set(7, goodsItem);
        set(8, goodsIsStick);
        set(9, classifyId);
    }
}
