/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.TableTime;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTimeRecord extends UpdatableRecordImpl<TableTimeRecord> implements Record2<String, Timestamp> {

    private static final long serialVersionUID = -727715248;

    /**
     * Setter for <code>xyf.table_time.table_name</code>.
     */
    public void setTableName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.table_time.table_name</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getTableName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xyf.table_time.deal_time</code>.
     */
    public void setDealTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.table_time.deal_time</code>.
     */
    @NotNull
    public Timestamp getDealTime() {
        return (Timestamp) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TableTime.TABLE_TIME.TABLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TableTime.TABLE_TIME.DEAL_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDealTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDealTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableTimeRecord value1(String value) {
        setTableName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableTimeRecord value2(Timestamp value) {
        setDealTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableTimeRecord values(String value1, Timestamp value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableTimeRecord
     */
    public TableTimeRecord() {
        super(TableTime.TABLE_TIME);
    }

    /**
     * Create a detached, initialised TableTimeRecord
     */
    public TableTimeRecord(String tableName, Timestamp dealTime) {
        super(TableTime.TABLE_TIME);

        set(0, tableName);
        set(1, dealTime);
    }
}
