/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.records;


import com.rongxingyn.xyf.domain.tables.Users;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record13<String, String, Byte, Byte, Byte, Byte, String, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = 572294429;

    /**
     * Setter for <code>xyf.users.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xyf.users.username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xyf.users.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xyf.users.password</code>.
     */
    @NotNull
    @Size(max = 300)
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xyf.users.disabled</code>.
     */
    public void setDisabled(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>xyf.users.disabled</code>.
     */
    public Byte getDisabled() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>xyf.users.account_expired</code>.
     */
    public void setAccountExpired(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>xyf.users.account_expired</code>.
     */
    public Byte getAccountExpired() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>xyf.users.account_locked</code>.
     */
    public void setAccountLocked(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>xyf.users.account_locked</code>.
     */
    public Byte getAccountLocked() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>xyf.users.credentials_expired</code>.
     */
    public void setCredentialsExpired(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>xyf.users.credentials_expired</code>.
     */
    public Byte getCredentialsExpired() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>xyf.users.address</code>.
     */
    public void setAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xyf.users.address</code>.
     */
    @Size(max = 200)
    public String getAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xyf.users.real_name</code>.
     */
    public void setRealName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>xyf.users.real_name</code>.
     */
    @Size(max = 10)
    public String getRealName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>xyf.users.sex</code>.
     */
    public void setSex(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>xyf.users.sex</code>.
     */
    @Size(max = 2)
    public String getSex() {
        return (String) get(8);
    }

    /**
     * Setter for <code>xyf.users.contact</code>.
     */
    public void setContact(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>xyf.users.contact</code>.
     */
    @Size(max = 20)
    public String getContact() {
        return (String) get(9);
    }

    /**
     * Setter for <code>xyf.users.access_token</code>.
     */
    public void setAccessToken(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>xyf.users.access_token</code>.
     */
    @Size(max = 64)
    public String getAccessToken() {
        return (String) get(10);
    }

    /**
     * Setter for <code>xyf.users.token_expired_date</code>.
     */
    public void setTokenExpiredDate(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>xyf.users.token_expired_date</code>.
     */
    public Timestamp getTokenExpiredDate() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>xyf.users.photo</code>.
     */
    public void setPhoto(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>xyf.users.photo</code>.
     */
    @Size(max = 100)
    public String getPhoto() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, Byte, Byte, Byte, Byte, String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, Byte, Byte, Byte, Byte, String, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Users.USERS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Users.USERS.DISABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Users.USERS.ACCOUNT_EXPIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Users.USERS.ACCOUNT_LOCKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Users.USERS.CREDENTIALS_EXPIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users.USERS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Users.USERS.REAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users.USERS.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Users.USERS.CONTACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Users.USERS.ACCESS_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Users.USERS.TOKEN_EXPIRED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Users.USERS.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getAccountExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getAccountLocked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getContact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getTokenExpiredDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getAccountExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getAccountLocked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getContact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getTokenExpiredDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(Byte value) {
        setDisabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Byte value) {
        setAccountExpired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(Byte value) {
        setAccountLocked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(Byte value) {
        setCredentialsExpired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(String value) {
        setRealName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(String value) {
        setContact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(String value) {
        setAccessToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value12(Timestamp value) {
        setTokenExpiredDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value13(String value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(String value1, String value2, Byte value3, Byte value4, Byte value5, Byte value6, String value7, String value8, String value9, String value10, String value11, Timestamp value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String username, String password, Byte disabled, Byte accountExpired, Byte accountLocked, Byte credentialsExpired, String address, String realName, String sex, String contact, String accessToken, Timestamp tokenExpiredDate, String photo) {
        super(Users.USERS);

        set(0, username);
        set(1, password);
        set(2, disabled);
        set(3, accountExpired);
        set(4, accountLocked);
        set(5, credentialsExpired);
        set(6, address);
        set(7, realName);
        set(8, sex);
        set(9, contact);
        set(10, accessToken);
        set(11, tokenExpiredDate);
        set(12, photo);
    }
}
