/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables;


import com.rongxingyn.xyf.domain.Indexes;
import com.rongxingyn.xyf.domain.Keys;
import com.rongxingyn.xyf.domain.Xyf;
import com.rongxingyn.xyf.domain.tables.records.ChannelInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelInfo extends TableImpl<ChannelInfoRecord> {

    private static final long serialVersionUID = 68144866;

    /**
     * The reference instance of <code>xyf.channel_info</code>
     */
    public static final ChannelInfo CHANNEL_INFO = new ChannelInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChannelInfoRecord> getRecordType() {
        return ChannelInfoRecord.class;
    }

    /**
     * The column <code>xyf.channel_info.channel_id</code>.
     */
    public final TableField<ChannelInfoRecord, String> CHANNEL_ID = createField("channel_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>xyf.channel_info.channel_name</code>.
     */
    public final TableField<ChannelInfoRecord, String> CHANNEL_NAME = createField("channel_name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * Create a <code>xyf.channel_info</code> table reference
     */
    public ChannelInfo() {
        this(DSL.name("channel_info"), null);
    }

    /**
     * Create an aliased <code>xyf.channel_info</code> table reference
     */
    public ChannelInfo(String alias) {
        this(DSL.name(alias), CHANNEL_INFO);
    }

    /**
     * Create an aliased <code>xyf.channel_info</code> table reference
     */
    public ChannelInfo(Name alias) {
        this(alias, CHANNEL_INFO);
    }

    private ChannelInfo(Name alias, Table<ChannelInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChannelInfo(Name alias, Table<ChannelInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xyf.XYF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHANNEL_INFO_CHANNEL_NAME, Indexes.CHANNEL_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChannelInfoRecord> getPrimaryKey() {
        return Keys.KEY_CHANNEL_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChannelInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<ChannelInfoRecord>>asList(Keys.KEY_CHANNEL_INFO_PRIMARY, Keys.KEY_CHANNEL_INFO_CHANNEL_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelInfo as(String alias) {
        return new ChannelInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelInfo as(Name alias) {
        return new ChannelInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelInfo rename(String name) {
        return new ChannelInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelInfo rename(Name name) {
        return new ChannelInfo(name, null);
    }
}
