/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables;


import com.rongxingyn.xyf.domain.Indexes;
import com.rongxingyn.xyf.domain.Keys;
import com.rongxingyn.xyf.domain.Xyf;
import com.rongxingyn.xyf.domain.tables.records.ClassifyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classify extends TableImpl<ClassifyRecord> {

    private static final long serialVersionUID = -1964134616;

    /**
     * The reference instance of <code>xyf.classify</code>
     */
    public static final Classify CLASSIFY = new Classify();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassifyRecord> getRecordType() {
        return ClassifyRecord.class;
    }

    /**
     * The column <code>xyf.classify.classify_id</code>.
     */
    public final TableField<ClassifyRecord, Integer> CLASSIFY_ID = createField("classify_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>xyf.classify.classify_name</code>.
     */
    public final TableField<ClassifyRecord, String> CLASSIFY_NAME = createField("classify_name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>xyf.classify.classify_is_del</code>.
     */
    public final TableField<ClassifyRecord, Byte> CLASSIFY_IS_DEL = createField("classify_is_del", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>xyf.classify</code> table reference
     */
    public Classify() {
        this(DSL.name("classify"), null);
    }

    /**
     * Create an aliased <code>xyf.classify</code> table reference
     */
    public Classify(String alias) {
        this(DSL.name(alias), CLASSIFY);
    }

    /**
     * Create an aliased <code>xyf.classify</code> table reference
     */
    public Classify(Name alias) {
        this(alias, CLASSIFY);
    }

    private Classify(Name alias, Table<ClassifyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Classify(Name alias, Table<ClassifyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xyf.XYF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLASSIFY_CLASSIFY_NAME, Indexes.CLASSIFY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClassifyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CLASSIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClassifyRecord> getPrimaryKey() {
        return Keys.KEY_CLASSIFY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClassifyRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassifyRecord>>asList(Keys.KEY_CLASSIFY_PRIMARY, Keys.KEY_CLASSIFY_CLASSIFY_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Classify as(String alias) {
        return new Classify(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Classify as(Name alias) {
        return new Classify(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Classify rename(String name) {
        return new Classify(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Classify rename(Name name) {
        return new Classify(name, null);
    }
}
