/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables;


import com.rongxingyn.xyf.domain.Indexes;
import com.rongxingyn.xyf.domain.Keys;
import com.rongxingyn.xyf.domain.Xyf;
import com.rongxingyn.xyf.domain.tables.records.ShopInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopInfo extends TableImpl<ShopInfoRecord> {

    private static final long serialVersionUID = 1637128794;

    /**
     * The reference instance of <code>xyf.shop_info</code>
     */
    public static final ShopInfo SHOP_INFO = new ShopInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopInfoRecord> getRecordType() {
        return ShopInfoRecord.class;
    }

    /**
     * The column <code>xyf.shop_info.shop_id</code>.
     */
    public final TableField<ShopInfoRecord, Integer> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>xyf.shop_info.shop_name</code>.
     */
    public final TableField<ShopInfoRecord, String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>xyf.shop_info.shop_brief</code>.
     */
    public final TableField<ShopInfoRecord, String> SHOP_BRIEF = createField("shop_brief", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>xyf.shop_info</code> table reference
     */
    public ShopInfo() {
        this(DSL.name("shop_info"), null);
    }

    /**
     * Create an aliased <code>xyf.shop_info</code> table reference
     */
    public ShopInfo(String alias) {
        this(DSL.name(alias), SHOP_INFO);
    }

    /**
     * Create an aliased <code>xyf.shop_info</code> table reference
     */
    public ShopInfo(Name alias) {
        this(alias, SHOP_INFO);
    }

    private ShopInfo(Name alias, Table<ShopInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private ShopInfo(Name alias, Table<ShopInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xyf.XYF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SHOP_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ShopInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SHOP_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ShopInfoRecord> getPrimaryKey() {
        return Keys.KEY_SHOP_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ShopInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<ShopInfoRecord>>asList(Keys.KEY_SHOP_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopInfo as(String alias) {
        return new ShopInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopInfo as(Name alias) {
        return new ShopInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopInfo rename(String name) {
        return new ShopInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopInfo rename(Name name) {
        return new ShopInfo(name, null);
    }
}
