/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables;


import com.rongxingyn.xyf.domain.Indexes;
import com.rongxingyn.xyf.domain.Keys;
import com.rongxingyn.xyf.domain.Xyf;
import com.rongxingyn.xyf.domain.tables.records.TableTimeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTime extends TableImpl<TableTimeRecord> {

    private static final long serialVersionUID = -1631497583;

    /**
     * The reference instance of <code>xyf.table_time</code>
     */
    public static final TableTime TABLE_TIME = new TableTime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TableTimeRecord> getRecordType() {
        return TableTimeRecord.class;
    }

    /**
     * The column <code>xyf.table_time.table_name</code>.
     */
    public final TableField<TableTimeRecord, String> TABLE_NAME = createField("table_name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>xyf.table_time.deal_time</code>.
     */
    public final TableField<TableTimeRecord, Timestamp> DEAL_TIME = createField("deal_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>xyf.table_time</code> table reference
     */
    public TableTime() {
        this(DSL.name("table_time"), null);
    }

    /**
     * Create an aliased <code>xyf.table_time</code> table reference
     */
    public TableTime(String alias) {
        this(DSL.name(alias), TABLE_TIME);
    }

    /**
     * Create an aliased <code>xyf.table_time</code> table reference
     */
    public TableTime(Name alias) {
        this(alias, TABLE_TIME);
    }

    private TableTime(Name alias, Table<TableTimeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TableTime(Name alias, Table<TableTimeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xyf.XYF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TABLE_TIME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TableTimeRecord> getPrimaryKey() {
        return Keys.KEY_TABLE_TIME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TableTimeRecord>> getKeys() {
        return Arrays.<UniqueKey<TableTimeRecord>>asList(Keys.KEY_TABLE_TIME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableTime as(String alias) {
        return new TableTime(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableTime as(Name alias) {
        return new TableTime(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TableTime rename(String name) {
        return new TableTime(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TableTime rename(Name name) {
        return new TableTime(name, null);
    }
}
