/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain;


import com.rongxingyn.xyf.domain.tables.Authorities;
import com.rongxingyn.xyf.domain.tables.Banner;
import com.rongxingyn.xyf.domain.tables.Classify;
import com.rongxingyn.xyf.domain.tables.DataInfo;
import com.rongxingyn.xyf.domain.tables.Feedback;
import com.rongxingyn.xyf.domain.tables.Goods;
import com.rongxingyn.xyf.domain.tables.GoodsPics;
import com.rongxingyn.xyf.domain.tables.ShopInfo;
import com.rongxingyn.xyf.domain.tables.TableTime;
import com.rongxingyn.xyf.domain.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>xyf</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHORITIES_PRIMARY = Indexes0.AUTHORITIES_PRIMARY;
    public static final Index BANNER_CLASSIFY_ID = Indexes0.BANNER_CLASSIFY_ID;
    public static final Index BANNER_PRIMARY = Indexes0.BANNER_PRIMARY;
    public static final Index CLASSIFY_CLASSIFY_NAME = Indexes0.CLASSIFY_CLASSIFY_NAME;
    public static final Index CLASSIFY_PRIMARY = Indexes0.CLASSIFY_PRIMARY;
    public static final Index DATA_INFO_PRIMARY = Indexes0.DATA_INFO_PRIMARY;
    public static final Index FEEDBACK_PRIMARY = Indexes0.FEEDBACK_PRIMARY;
    public static final Index GOODS_CLASSIFY_ID = Indexes0.GOODS_CLASSIFY_ID;
    public static final Index GOODS_GOODS_NAME = Indexes0.GOODS_GOODS_NAME;
    public static final Index GOODS_PRIMARY = Indexes0.GOODS_PRIMARY;
    public static final Index GOODS_PICS_GOODS_ID = Indexes0.GOODS_PICS_GOODS_ID;
    public static final Index GOODS_PICS_PRIMARY = Indexes0.GOODS_PICS_PRIMARY;
    public static final Index SHOP_INFO_PRIMARY = Indexes0.SHOP_INFO_PRIMARY;
    public static final Index TABLE_TIME_PRIMARY = Indexes0.TABLE_TIME_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHORITIES_PRIMARY = Internal.createIndex("PRIMARY", Authorities.AUTHORITIES, new OrderField[] { Authorities.AUTHORITIES.USERNAME, Authorities.AUTHORITIES.AUTHORITY }, true);
        public static Index BANNER_CLASSIFY_ID = Internal.createIndex("classify_id", Banner.BANNER, new OrderField[] { Banner.BANNER.CLASSIFY_ID }, false);
        public static Index BANNER_PRIMARY = Internal.createIndex("PRIMARY", Banner.BANNER, new OrderField[] { Banner.BANNER.BANNER_ID }, true);
        public static Index CLASSIFY_CLASSIFY_NAME = Internal.createIndex("classify_name", Classify.CLASSIFY, new OrderField[] { Classify.CLASSIFY.CLASSIFY_NAME }, true);
        public static Index CLASSIFY_PRIMARY = Internal.createIndex("PRIMARY", Classify.CLASSIFY, new OrderField[] { Classify.CLASSIFY.CLASSIFY_ID }, true);
        public static Index DATA_INFO_PRIMARY = Internal.createIndex("PRIMARY", DataInfo.DATA_INFO, new OrderField[] { DataInfo.DATA_INFO.DATA_KEY }, true);
        public static Index FEEDBACK_PRIMARY = Internal.createIndex("PRIMARY", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.FEEDBACK_ID }, true);
        public static Index GOODS_CLASSIFY_ID = Internal.createIndex("classify_id", Goods.GOODS, new OrderField[] { Goods.GOODS.CLASSIFY_ID }, false);
        public static Index GOODS_GOODS_NAME = Internal.createIndex("goods_name", Goods.GOODS, new OrderField[] { Goods.GOODS.GOODS_NAME }, true);
        public static Index GOODS_PRIMARY = Internal.createIndex("PRIMARY", Goods.GOODS, new OrderField[] { Goods.GOODS.GOODS_ID }, true);
        public static Index GOODS_PICS_GOODS_ID = Internal.createIndex("goods_id", GoodsPics.GOODS_PICS, new OrderField[] { GoodsPics.GOODS_PICS.GOODS_ID }, false);
        public static Index GOODS_PICS_PRIMARY = Internal.createIndex("PRIMARY", GoodsPics.GOODS_PICS, new OrderField[] { GoodsPics.GOODS_PICS.PIC_ID }, true);
        public static Index SHOP_INFO_PRIMARY = Internal.createIndex("PRIMARY", ShopInfo.SHOP_INFO, new OrderField[] { ShopInfo.SHOP_INFO.SHOP_ID }, true);
        public static Index TABLE_TIME_PRIMARY = Internal.createIndex("PRIMARY", TableTime.TABLE_TIME, new OrderField[] { TableTime.TABLE_TIME.TABLE_NAME }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.USERNAME }, true);
    }
}
