/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain;


import com.rongxingyn.xyf.domain.tables.Authorities;
import com.rongxingyn.xyf.domain.tables.PersistentLogins;
import com.rongxingyn.xyf.domain.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in xyf
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>xyf.authorities</code>.
     */
    public static final Authorities AUTHORITIES = com.rongxingyn.xyf.domain.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>xyf.persistent_logins</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = com.rongxingyn.xyf.domain.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>xyf.users</code>.
     */
    public static final Users USERS = com.rongxingyn.xyf.domain.tables.Users.USERS;
}
