/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain;


import com.rongxingyn.xyf.domain.tables.Authorities;
import com.rongxingyn.xyf.domain.tables.Banner;
import com.rongxingyn.xyf.domain.tables.Classify;
import com.rongxingyn.xyf.domain.tables.DataInfo;
import com.rongxingyn.xyf.domain.tables.Feedback;
import com.rongxingyn.xyf.domain.tables.Goods;
import com.rongxingyn.xyf.domain.tables.GoodsPics;
import com.rongxingyn.xyf.domain.tables.ShopInfo;
import com.rongxingyn.xyf.domain.tables.TableTime;
import com.rongxingyn.xyf.domain.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in xyf
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>xyf.authorities</code>.
     */
    public static final Authorities AUTHORITIES = com.rongxingyn.xyf.domain.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>xyf.banner</code>.
     */
    public static final Banner BANNER = com.rongxingyn.xyf.domain.tables.Banner.BANNER;

    /**
     * The table <code>xyf.classify</code>.
     */
    public static final Classify CLASSIFY = com.rongxingyn.xyf.domain.tables.Classify.CLASSIFY;

    /**
     * The table <code>xyf.data_info</code>.
     */
    public static final DataInfo DATA_INFO = com.rongxingyn.xyf.domain.tables.DataInfo.DATA_INFO;

    /**
     * The table <code>xyf.feedback</code>.
     */
    public static final Feedback FEEDBACK = com.rongxingyn.xyf.domain.tables.Feedback.FEEDBACK;

    /**
     * The table <code>xyf.goods</code>.
     */
    public static final Goods GOODS = com.rongxingyn.xyf.domain.tables.Goods.GOODS;

    /**
     * The table <code>xyf.goods_pics</code>.
     */
    public static final GoodsPics GOODS_PICS = com.rongxingyn.xyf.domain.tables.GoodsPics.GOODS_PICS;

    /**
     * The table <code>xyf.shop_info</code>.
     */
    public static final ShopInfo SHOP_INFO = com.rongxingyn.xyf.domain.tables.ShopInfo.SHOP_INFO;

    /**
     * The table <code>xyf.table_time</code>.
     */
    public static final TableTime TABLE_TIME = com.rongxingyn.xyf.domain.tables.TableTime.TABLE_TIME;

    /**
     * The table <code>xyf.users</code>.
     */
    public static final Users USERS = com.rongxingyn.xyf.domain.tables.Users.USERS;
}
