/*
 * This file is generated by jOOQ.
 */
package com.rongxingyn.xyf.domain;


import com.rongxingyn.xyf.domain.tables.Authorities;
import com.rongxingyn.xyf.domain.tables.PersistentLogins;
import com.rongxingyn.xyf.domain.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Xyf extends SchemaImpl {

    /**
     * The reference instance of <code>xyf</code>
     */
    public static final Xyf XYF = new Xyf();
    private static final long serialVersionUID = -535106949;
    /**
     * The table <code>xyf.authorities</code>.
     */
    public final Authorities AUTHORITIES = com.rongxingyn.xyf.domain.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>xyf.persistent_logins</code>.
     */
    public final PersistentLogins PERSISTENT_LOGINS = com.rongxingyn.xyf.domain.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>xyf.users</code>.
     */
    public final Users USERS = com.rongxingyn.xyf.domain.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Xyf() {
        super("xyf", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Authorities.AUTHORITIES,
                PersistentLogins.PERSISTENT_LOGINS,
                Users.USERS);
    }
}
