/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Banner implements Serializable {

    private static final long serialVersionUID = -105775541;

    private String  bannerId;
    private Integer bannerSerial;
    private String  bannerUrl;
    private Byte    isHide;
    private Integer classifyId;

    public Banner() {}

    public Banner(Banner value) {
        this.bannerId = value.bannerId;
        this.bannerSerial = value.bannerSerial;
        this.bannerUrl = value.bannerUrl;
        this.isHide = value.isHide;
        this.classifyId = value.classifyId;
    }

    public Banner(
        String  bannerId,
        Integer bannerSerial,
        String  bannerUrl,
        Byte    isHide,
        Integer classifyId
    ) {
        this.bannerId = bannerId;
        this.bannerSerial = bannerSerial;
        this.bannerUrl = bannerUrl;
        this.isHide = isHide;
        this.classifyId = classifyId;
    }

    @NotNull
    @Size(max = 64)
    public String getBannerId() {
        return this.bannerId;
    }

    public void setBannerId(String bannerId) {
        this.bannerId = bannerId;
    }

    public Integer getBannerSerial() {
        return this.bannerSerial;
    }

    public void setBannerSerial(Integer bannerSerial) {
        this.bannerSerial = bannerSerial;
    }

    @NotNull
    @Size(max = 500)
    public String getBannerUrl() {
        return this.bannerUrl;
    }

    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }

    public Byte getIsHide() {
        return this.isHide;
    }

    public void setIsHide(Byte isHide) {
        this.isHide = isHide;
    }

    @NotNull
    public Integer getClassifyId() {
        return this.classifyId;
    }

    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Banner (");

        sb.append(bannerId);
        sb.append(", ").append(bannerSerial);
        sb.append(", ").append(bannerUrl);
        sb.append(", ").append(isHide);
        sb.append(", ").append(classifyId);

        sb.append(")");
        return sb.toString();
    }
}
