/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Banner implements Serializable {

    private static final long serialVersionUID = 305342565;

    private String  bannerId;
    private Integer bannerSerial;
    private String  bannerUrl;
    private Byte    bannerIsHide;
    private Integer bannerItem;

    public Banner() {}

    public Banner(Banner value) {
        this.bannerId = value.bannerId;
        this.bannerSerial = value.bannerSerial;
        this.bannerUrl = value.bannerUrl;
        this.bannerIsHide = value.bannerIsHide;
        this.bannerItem = value.bannerItem;
    }

    public Banner(
        String  bannerId,
        Integer bannerSerial,
        String  bannerUrl,
        Byte    bannerIsHide,
        Integer bannerItem
    ) {
        this.bannerId = bannerId;
        this.bannerSerial = bannerSerial;
        this.bannerUrl = bannerUrl;
        this.bannerIsHide = bannerIsHide;
        this.bannerItem = bannerItem;
    }

    @NotNull
    @Size(max = 64)
    public String getBannerId() {
        return this.bannerId;
    }

    public void setBannerId(String bannerId) {
        this.bannerId = bannerId;
    }

    public Integer getBannerSerial() {
        return this.bannerSerial;
    }

    public void setBannerSerial(Integer bannerSerial) {
        this.bannerSerial = bannerSerial;
    }

    @NotNull
    @Size(max = 500)
    public String getBannerUrl() {
        return this.bannerUrl;
    }

    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }

    public Byte getBannerIsHide() {
        return this.bannerIsHide;
    }

    public void setBannerIsHide(Byte bannerIsHide) {
        this.bannerIsHide = bannerIsHide;
    }

    public Integer getBannerItem() {
        return this.bannerItem;
    }

    public void setBannerItem(Integer bannerItem) {
        this.bannerItem = bannerItem;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Banner (");

        sb.append(bannerId);
        sb.append(", ").append(bannerSerial);
        sb.append(", ").append(bannerUrl);
        sb.append(", ").append(bannerIsHide);
        sb.append(", ").append(bannerItem);

        sb.append(")");
        return sb.toString();
    }
}
