/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelInfo implements Serializable {

    private static final long serialVersionUID = -400631579;

    private String channelId;
    private String channelName;

    public ChannelInfo() {}

    public ChannelInfo(ChannelInfo value) {
        this.channelId = value.channelId;
        this.channelName = value.channelName;
    }

    public ChannelInfo(
        String channelId,
        String channelName
    ) {
        this.channelId = channelId;
        this.channelName = channelName;
    }

    @NotNull
    @Size(max = 64)
    public String getChannelId() {
        return this.channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    @NotNull
    @Size(max = 20)
    public String getChannelName() {
        return this.channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChannelInfo (");

        sb.append(channelId);
        sb.append(", ").append(channelName);

        sb.append(")");
        return sb.toString();
    }
}
