/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataInfo implements Serializable {

    private static final long serialVersionUID = 845836397;

    private String dataKey;
    private String dataValue;

    public DataInfo() {}

    public DataInfo(DataInfo value) {
        this.dataKey = value.dataKey;
        this.dataValue = value.dataValue;
    }

    public DataInfo(
        String dataKey,
        String dataValue
    ) {
        this.dataKey = dataKey;
        this.dataValue = dataValue;
    }

    @NotNull
    @Size(max = 200)
    public String getDataKey() {
        return this.dataKey;
    }

    public void setDataKey(String dataKey) {
        this.dataKey = dataKey;
    }

    @NotNull
    @Size(max = 600)
    public String getDataValue() {
        return this.dataValue;
    }

    public void setDataValue(String dataValue) {
        this.dataValue = dataValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataInfo (");

        sb.append(dataKey);
        sb.append(", ").append(dataValue);

        sb.append(")");
        return sb.toString();
    }
}
