/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Feedback implements Serializable {

    private static final long serialVersionUID = 1234771759;

    private Integer   feedbackId;
    private String    customerName;
    private String    customerContact;
    private String    content;
    private Timestamp createDate;
    private Byte      hasDeal;
    private String    remark;

    public Feedback() {}

    public Feedback(Feedback value) {
        this.feedbackId = value.feedbackId;
        this.customerName = value.customerName;
        this.customerContact = value.customerContact;
        this.content = value.content;
        this.createDate = value.createDate;
        this.hasDeal = value.hasDeal;
        this.remark = value.remark;
    }

    public Feedback(
        Integer   feedbackId,
        String    customerName,
        String    customerContact,
        String    content,
        Timestamp createDate,
        Byte      hasDeal,
        String    remark
    ) {
        this.feedbackId = feedbackId;
        this.customerName = customerName;
        this.customerContact = customerContact;
        this.content = content;
        this.createDate = createDate;
        this.hasDeal = hasDeal;
        this.remark = remark;
    }

    public Integer getFeedbackId() {
        return this.feedbackId;
    }

    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    @NotNull
    @Size(max = 20)
    public String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @NotNull
    @Size(max = 100)
    public String getCustomerContact() {
        return this.customerContact;
    }

    public void setCustomerContact(String customerContact) {
        this.customerContact = customerContact;
    }

    @NotNull
    @Size(max = 500)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @NotNull
    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Byte getHasDeal() {
        return this.hasDeal;
    }

    public void setHasDeal(Byte hasDeal) {
        this.hasDeal = hasDeal;
    }

    @Size(max = 200)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Feedback (");

        sb.append(feedbackId);
        sb.append(", ").append(customerName);
        sb.append(", ").append(customerContact);
        sb.append(", ").append(content);
        sb.append(", ").append(createDate);
        sb.append(", ").append(hasDeal);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
