/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsPics implements Serializable {

    private static final long serialVersionUID = -1863972885;

    private Integer picId;
    private String  goodsId;
    private String  picUrl;

    public GoodsPics() {}

    public GoodsPics(GoodsPics value) {
        this.picId = value.picId;
        this.goodsId = value.goodsId;
        this.picUrl = value.picUrl;
    }

    public GoodsPics(
        Integer picId,
        String  goodsId,
        String  picUrl
    ) {
        this.picId = picId;
        this.goodsId = goodsId;
        this.picUrl = picUrl;
    }

    public Integer getPicId() {
        return this.picId;
    }

    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    @NotNull
    @Size(max = 64)
    public String getGoodsId() {
        return this.goodsId;
    }

    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    @NotNull
    @Size(max = 500)
    public String getPicUrl() {
        return this.picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GoodsPics (");

        sb.append(picId);
        sb.append(", ").append(goodsId);
        sb.append(", ").append(picUrl);

        sb.append(")");
        return sb.toString();
    }
}
