/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Goods implements Serializable {

    private static final long serialVersionUID = 440895795;

    private String  goodsId;
    private String  goodsName;
    private Double  goodsPrice;
    private String  goodsBrief;
    private Integer goodsRecommend;
    private Byte    isStick;
    private Integer stickSerial;
    private Integer goodsSerial;
    private Integer classifyId;

    public Goods() {}

    public Goods(Goods value) {
        this.goodsId = value.goodsId;
        this.goodsName = value.goodsName;
        this.goodsPrice = value.goodsPrice;
        this.goodsBrief = value.goodsBrief;
        this.goodsRecommend = value.goodsRecommend;
        this.isStick = value.isStick;
        this.stickSerial = value.stickSerial;
        this.goodsSerial = value.goodsSerial;
        this.classifyId = value.classifyId;
    }

    public Goods(
        String  goodsId,
        String  goodsName,
        Double  goodsPrice,
        String  goodsBrief,
        Integer goodsRecommend,
        Byte    isStick,
        Integer stickSerial,
        Integer goodsSerial,
        Integer classifyId
    ) {
        this.goodsId = goodsId;
        this.goodsName = goodsName;
        this.goodsPrice = goodsPrice;
        this.goodsBrief = goodsBrief;
        this.goodsRecommend = goodsRecommend;
        this.isStick = isStick;
        this.stickSerial = stickSerial;
        this.goodsSerial = goodsSerial;
        this.classifyId = classifyId;
    }

    @NotNull
    @Size(max = 64)
    public String getGoodsId() {
        return this.goodsId;
    }

    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    @NotNull
    @Size(max = 100)
    public String getGoodsName() {
        return this.goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public Double getGoodsPrice() {
        return this.goodsPrice;
    }

    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    @Size(max = 200)
    public String getGoodsBrief() {
        return this.goodsBrief;
    }

    public void setGoodsBrief(String goodsBrief) {
        this.goodsBrief = goodsBrief;
    }

    public Integer getGoodsRecommend() {
        return this.goodsRecommend;
    }

    public void setGoodsRecommend(Integer goodsRecommend) {
        this.goodsRecommend = goodsRecommend;
    }

    public Byte getIsStick() {
        return this.isStick;
    }

    public void setIsStick(Byte isStick) {
        this.isStick = isStick;
    }

    public Integer getStickSerial() {
        return this.stickSerial;
    }

    public void setStickSerial(Integer stickSerial) {
        this.stickSerial = stickSerial;
    }

    public Integer getGoodsSerial() {
        return this.goodsSerial;
    }

    public void setGoodsSerial(Integer goodsSerial) {
        this.goodsSerial = goodsSerial;
    }

    @NotNull
    public Integer getClassifyId() {
        return this.classifyId;
    }

    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Goods (");

        sb.append(goodsId);
        sb.append(", ").append(goodsName);
        sb.append(", ").append(goodsPrice);
        sb.append(", ").append(goodsBrief);
        sb.append(", ").append(goodsRecommend);
        sb.append(", ").append(isStick);
        sb.append(", ").append(stickSerial);
        sb.append(", ").append(goodsSerial);
        sb.append(", ").append(classifyId);

        sb.append(")");
        return sb.toString();
    }
}
