/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestLog implements Serializable {

    private static final long serialVersionUID = -1402910646;

    private String    logId;
    private String    requestUrl;
    private String    requestParam;
    private String    result;
    private String    channelName;
    private Timestamp requestDate;

    public RequestLog() {}

    public RequestLog(RequestLog value) {
        this.logId = value.logId;
        this.requestUrl = value.requestUrl;
        this.requestParam = value.requestParam;
        this.result = value.result;
        this.channelName = value.channelName;
        this.requestDate = value.requestDate;
    }

    public RequestLog(
        String    logId,
        String    requestUrl,
        String    requestParam,
        String    result,
        String    channelName,
        Timestamp requestDate
    ) {
        this.logId = logId;
        this.requestUrl = requestUrl;
        this.requestParam = requestParam;
        this.result = result;
        this.channelName = channelName;
        this.requestDate = requestDate;
    }

    @NotNull
    @Size(max = 64)
    public String getLogId() {
        return this.logId;
    }

    public void setLogId(String logId) {
        this.logId = logId;
    }

    @Size(max = 100)
    public String getRequestUrl() {
        return this.requestUrl;
    }

    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    @Size(max = 500)
    public String getRequestParam() {
        return this.requestParam;
    }

    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam;
    }

    @Size(max = 500)
    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    @Size(max = 20)
    public String getChannelName() {
        return this.channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    @NotNull
    public Timestamp getRequestDate() {
        return this.requestDate;
    }

    public void setRequestDate(Timestamp requestDate) {
        this.requestDate = requestDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RequestLog (");

        sb.append(logId);
        sb.append(", ").append(requestUrl);
        sb.append(", ").append(requestParam);
        sb.append(", ").append(result);
        sb.append(", ").append(channelName);
        sb.append(", ").append(requestDate);

        sb.append(")");
        return sb.toString();
    }
}
