/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopInfo implements Serializable {

    private static final long serialVersionUID = -1431848155;

    private Integer shopId;
    private String  shopName;
    private String  shopBrief;

    public ShopInfo() {}

    public ShopInfo(ShopInfo value) {
        this.shopId = value.shopId;
        this.shopName = value.shopName;
        this.shopBrief = value.shopBrief;
    }

    public ShopInfo(
        Integer shopId,
        String  shopName,
        String  shopBrief
    ) {
        this.shopId = shopId;
        this.shopName = shopName;
        this.shopBrief = shopBrief;
    }

    public Integer getShopId() {
        return this.shopId;
    }

    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    @NotNull
    @Size(max = 200)
    public String getShopName() {
        return this.shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    @Size(max = 65535)
    public String getShopBrief() {
        return this.shopBrief;
    }

    public void setShopBrief(String shopBrief) {
        this.shopBrief = shopBrief;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShopInfo (");

        sb.append(shopId);
        sb.append(", ").append(shopName);
        sb.append(", ").append(shopBrief);

        sb.append(")");
        return sb.toString();
    }
}
