/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemApi implements Serializable {

    private static final long serialVersionUID = 937539953;

    private Integer apiId;
    private String  param;
    private String  remark;

    public SystemApi() {}

    public SystemApi(SystemApi value) {
        this.apiId = value.apiId;
        this.param = value.param;
        this.remark = value.remark;
    }

    public SystemApi(
        Integer apiId,
        String  param,
        String  remark
    ) {
        this.apiId = apiId;
        this.param = param;
        this.remark = remark;
    }

    public Integer getApiId() {
        return this.apiId;
    }

    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    @Size(max = 200)
    public String getParam() {
        return this.param;
    }

    public void setParam(String param) {
        this.param = param;
    }

    @Size(max = 500)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemApi (");

        sb.append(apiId);
        sb.append(", ").append(param);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
