/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTime implements Serializable {

    private static final long serialVersionUID = -771772914;

    private String    tableName;
    private Timestamp dealTime;

    public TableTime() {}

    public TableTime(TableTime value) {
        this.tableName = value.tableName;
        this.dealTime = value.dealTime;
    }

    public TableTime(
        String    tableName,
        Timestamp dealTime
    ) {
        this.tableName = tableName;
        this.dealTime = dealTime;
    }

    @NotNull
    @Size(max = 20)
    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    @NotNull
    public Timestamp getDealTime() {
        return this.dealTime;
    }

    public void setDealTime(Timestamp dealTime) {
        this.dealTime = dealTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TableTime (");

        sb.append(tableName);
        sb.append(", ").append(dealTime);

        sb.append(")");
        return sb.toString();
    }
}
