/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1687683443;

    private String    username;
    private String    password;
    private Byte      disabled;
    private Byte      accountExpired;
    private Byte      accountLocked;
    private Byte      credentialsExpired;
    private String    address;
    private String    realName;
    private String    sex;
    private String    contact;
    private String    accessToken;
    private Timestamp tokenExpiredDate;
    private String    photo;

    public Users() {}

    public Users(Users value) {
        this.username = value.username;
        this.password = value.password;
        this.disabled = value.disabled;
        this.accountExpired = value.accountExpired;
        this.accountLocked = value.accountLocked;
        this.credentialsExpired = value.credentialsExpired;
        this.address = value.address;
        this.realName = value.realName;
        this.sex = value.sex;
        this.contact = value.contact;
        this.accessToken = value.accessToken;
        this.tokenExpiredDate = value.tokenExpiredDate;
        this.photo = value.photo;
    }

    public Users(
        String    username,
        String    password,
        Byte      disabled,
        Byte      accountExpired,
        Byte      accountLocked,
        Byte      credentialsExpired,
        String    address,
        String    realName,
        String    sex,
        String    contact,
        String    accessToken,
        Timestamp tokenExpiredDate,
        String    photo
    ) {
        this.username = username;
        this.password = password;
        this.disabled = disabled;
        this.accountExpired = accountExpired;
        this.accountLocked = accountLocked;
        this.credentialsExpired = credentialsExpired;
        this.address = address;
        this.realName = realName;
        this.sex = sex;
        this.contact = contact;
        this.accessToken = accessToken;
        this.tokenExpiredDate = tokenExpiredDate;
        this.photo = photo;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 300)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Byte getDisabled() {
        return this.disabled;
    }

    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }

    public Byte getAccountExpired() {
        return this.accountExpired;
    }

    public void setAccountExpired(Byte accountExpired) {
        this.accountExpired = accountExpired;
    }

    public Byte getAccountLocked() {
        return this.accountLocked;
    }

    public void setAccountLocked(Byte accountLocked) {
        this.accountLocked = accountLocked;
    }

    public Byte getCredentialsExpired() {
        return this.credentialsExpired;
    }

    public void setCredentialsExpired(Byte credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }

    @Size(max = 200)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Size(max = 10)
    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    @Size(max = 2)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Size(max = 20)
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    @Size(max = 64)
    public String getAccessToken() {
        return this.accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public Timestamp getTokenExpiredDate() {
        return this.tokenExpiredDate;
    }

    public void setTokenExpiredDate(Timestamp tokenExpiredDate) {
        this.tokenExpiredDate = tokenExpiredDate;
    }

    @Size(max = 100)
    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(disabled);
        sb.append(", ").append(accountExpired);
        sb.append(", ").append(accountLocked);
        sb.append(", ").append(credentialsExpired);
        sb.append(", ").append(address);
        sb.append(", ").append(realName);
        sb.append(", ").append(sex);
        sb.append(", ").append(contact);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(tokenExpiredDate);
        sb.append(", ").append(photo);

        sb.append(")");
        return sb.toString();
    }
}
