/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -866517887;

    private String username;
    private String password;
    private Byte   disabled;
    private Byte   accountExpired;
    private Byte   accountLocked;
    private Byte   credentialsExpired;

    public Users() {}

    public Users(Users value) {
        this.username = value.username;
        this.password = value.password;
        this.disabled = value.disabled;
        this.accountExpired = value.accountExpired;
        this.accountLocked = value.accountLocked;
        this.credentialsExpired = value.credentialsExpired;
    }

    public Users(
        String username,
        String password,
        Byte   disabled,
        Byte   accountExpired,
        Byte   accountLocked,
        Byte   credentialsExpired
    ) {
        this.username = username;
        this.password = password;
        this.disabled = disabled;
        this.accountExpired = accountExpired;
        this.accountLocked = accountLocked;
        this.credentialsExpired = credentialsExpired;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 300)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Byte getDisabled() {
        return this.disabled;
    }

    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }

    public Byte getAccountExpired() {
        return this.accountExpired;
    }

    public void setAccountExpired(Byte accountExpired) {
        this.accountExpired = accountExpired;
    }

    public Byte getAccountLocked() {
        return this.accountLocked;
    }

    public void setAccountLocked(Byte accountLocked) {
        this.accountLocked = accountLocked;
    }

    public Byte getCredentialsExpired() {
        return this.credentialsExpired;
    }

    public void setCredentialsExpired(Byte credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(disabled);
        sb.append(", ").append(accountExpired);
        sb.append(", ").append(accountLocked);
        sb.append(", ").append(credentialsExpired);

        sb.append(")");
        return sb.toString();
    }
}
