/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.Banner;
import com.rongxingyn.xyf.domain.tables.records.BannerRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class BannerDao extends DAOImpl<BannerRecord, com.rongxingyn.xyf.domain.tables.pojos.Banner, String> {

    /**
     * Create a new BannerDao without any configuration
     */
    public BannerDao() {
        super(Banner.BANNER, com.rongxingyn.xyf.domain.tables.pojos.Banner.class);
    }

    /**
     * Create a new BannerDao with an attached configuration
     */
    @Autowired
    public BannerDao(Configuration configuration) {
        super(Banner.BANNER, com.rongxingyn.xyf.domain.tables.pojos.Banner.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.rongxingyn.xyf.domain.tables.pojos.Banner object) {
        return object.getBannerId();
    }

    /**
     * Fetch records that have <code>banner_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Banner> fetchByBannerId(String... values) {
        return fetch(Banner.BANNER.BANNER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>banner_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.Banner fetchOneByBannerId(String value) {
        return fetchOne(Banner.BANNER.BANNER_ID, value);
    }

    /**
     * Fetch records that have <code>banner_serial IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Banner> fetchByBannerSerial(Integer... values) {
        return fetch(Banner.BANNER.BANNER_SERIAL, values);
    }

    /**
     * Fetch records that have <code>banner_url IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Banner> fetchByBannerUrl(String... values) {
        return fetch(Banner.BANNER.BANNER_URL, values);
    }

    /**
     * Fetch records that have <code>is_hide IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Banner> fetchByIsHide(Byte... values) {
        return fetch(Banner.BANNER.IS_HIDE, values);
    }

    /**
     * Fetch records that have <code>classify_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Banner> fetchByClassifyId(Integer... values) {
        return fetch(Banner.BANNER.CLASSIFY_ID, values);
    }
}
