/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.ChannelInfo;
import com.rongxingyn.xyf.domain.tables.records.ChannelInfoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ChannelInfoDao extends DAOImpl<ChannelInfoRecord, com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo, String> {

    /**
     * Create a new ChannelInfoDao without any configuration
     */
    public ChannelInfoDao() {
        super(ChannelInfo.CHANNEL_INFO, com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo.class);
    }

    /**
     * Create a new ChannelInfoDao with an attached configuration
     */
    @Autowired
    public ChannelInfoDao(Configuration configuration) {
        super(ChannelInfo.CHANNEL_INFO, com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo object) {
        return object.getChannelId();
    }

    /**
     * Fetch records that have <code>channel_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo> fetchByChannelId(String... values) {
        return fetch(ChannelInfo.CHANNEL_INFO.CHANNEL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>channel_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo fetchOneByChannelId(String value) {
        return fetchOne(ChannelInfo.CHANNEL_INFO.CHANNEL_ID, value);
    }

    /**
     * Fetch records that have <code>channel_name IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo> fetchByChannelName(String... values) {
        return fetch(ChannelInfo.CHANNEL_INFO.CHANNEL_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>channel_name = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.ChannelInfo fetchOneByChannelName(String value) {
        return fetchOne(ChannelInfo.CHANNEL_INFO.CHANNEL_NAME, value);
    }
}
