/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.Classify;
import com.rongxingyn.xyf.domain.tables.records.ClassifyRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ClassifyDao extends DAOImpl<ClassifyRecord, com.rongxingyn.xyf.domain.tables.pojos.Classify, Integer> {

    /**
     * Create a new ClassifyDao without any configuration
     */
    public ClassifyDao() {
        super(Classify.CLASSIFY, com.rongxingyn.xyf.domain.tables.pojos.Classify.class);
    }

    /**
     * Create a new ClassifyDao with an attached configuration
     */
    @Autowired
    public ClassifyDao(Configuration configuration) {
        super(Classify.CLASSIFY, com.rongxingyn.xyf.domain.tables.pojos.Classify.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.rongxingyn.xyf.domain.tables.pojos.Classify object) {
        return object.getClassifyId();
    }

    /**
     * Fetch records that have <code>classify_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Classify> fetchByClassifyId(Integer... values) {
        return fetch(Classify.CLASSIFY.CLASSIFY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>classify_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.Classify fetchOneByClassifyId(Integer value) {
        return fetchOne(Classify.CLASSIFY.CLASSIFY_ID, value);
    }

    /**
     * Fetch records that have <code>classify_name IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Classify> fetchByClassifyName(String... values) {
        return fetch(Classify.CLASSIFY.CLASSIFY_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>classify_name = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.Classify fetchOneByClassifyName(String value) {
        return fetchOne(Classify.CLASSIFY.CLASSIFY_NAME, value);
    }
}
