/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.Feedback;
import com.rongxingyn.xyf.domain.tables.records.FeedbackRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class FeedbackDao extends DAOImpl<FeedbackRecord, com.rongxingyn.xyf.domain.tables.pojos.Feedback, Integer> {

    /**
     * Create a new FeedbackDao without any configuration
     */
    public FeedbackDao() {
        super(Feedback.FEEDBACK, com.rongxingyn.xyf.domain.tables.pojos.Feedback.class);
    }

    /**
     * Create a new FeedbackDao with an attached configuration
     */
    @Autowired
    public FeedbackDao(Configuration configuration) {
        super(Feedback.FEEDBACK, com.rongxingyn.xyf.domain.tables.pojos.Feedback.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.rongxingyn.xyf.domain.tables.pojos.Feedback object) {
        return object.getFeedbackId();
    }

    /**
     * Fetch records that have <code>feedback_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Feedback> fetchByFeedbackId(Integer... values) {
        return fetch(Feedback.FEEDBACK.FEEDBACK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>feedback_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.Feedback fetchOneByFeedbackId(Integer value) {
        return fetchOne(Feedback.FEEDBACK.FEEDBACK_ID, value);
    }

    /**
     * Fetch records that have <code>customer_name IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Feedback> fetchByCustomerName(String... values) {
        return fetch(Feedback.FEEDBACK.CUSTOMER_NAME, values);
    }

    /**
     * Fetch records that have <code>customer_contact IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Feedback> fetchByCustomerContact(String... values) {
        return fetch(Feedback.FEEDBACK.CUSTOMER_CONTACT, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Feedback> fetchByContent(String... values) {
        return fetch(Feedback.FEEDBACK.CONTENT, values);
    }

    /**
     * Fetch records that have <code>has_deal IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Feedback> fetchByHasDeal(Byte... values) {
        return fetch(Feedback.FEEDBACK.HAS_DEAL, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.Feedback> fetchByRemark(String... values) {
        return fetch(Feedback.FEEDBACK.REMARK, values);
    }
}
