/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.GoodsPics;
import com.rongxingyn.xyf.domain.tables.records.GoodsPicsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class GoodsPicsDao extends DAOImpl<GoodsPicsRecord, com.rongxingyn.xyf.domain.tables.pojos.GoodsPics, Integer> {

    /**
     * Create a new GoodsPicsDao without any configuration
     */
    public GoodsPicsDao() {
        super(GoodsPics.GOODS_PICS, com.rongxingyn.xyf.domain.tables.pojos.GoodsPics.class);
    }

    /**
     * Create a new GoodsPicsDao with an attached configuration
     */
    @Autowired
    public GoodsPicsDao(Configuration configuration) {
        super(GoodsPics.GOODS_PICS, com.rongxingyn.xyf.domain.tables.pojos.GoodsPics.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.rongxingyn.xyf.domain.tables.pojos.GoodsPics object) {
        return object.getPicId();
    }

    /**
     * Fetch records that have <code>pic_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.GoodsPics> fetchByPicId(Integer... values) {
        return fetch(GoodsPics.GOODS_PICS.PIC_ID, values);
    }

    /**
     * Fetch a unique record that has <code>pic_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.GoodsPics fetchOneByPicId(Integer value) {
        return fetchOne(GoodsPics.GOODS_PICS.PIC_ID, value);
    }

    /**
     * Fetch records that have <code>goods_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.GoodsPics> fetchByGoodsId(String... values) {
        return fetch(GoodsPics.GOODS_PICS.GOODS_ID, values);
    }

    /**
     * Fetch records that have <code>pic_url IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.GoodsPics> fetchByPicUrl(String... values) {
        return fetch(GoodsPics.GOODS_PICS.PIC_URL, values);
    }
}
