/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.RequestLog;
import com.rongxingyn.xyf.domain.tables.records.RequestLogRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RequestLogDao extends DAOImpl<RequestLogRecord, com.rongxingyn.xyf.domain.tables.pojos.RequestLog, String> {

    /**
     * Create a new RequestLogDao without any configuration
     */
    public RequestLogDao() {
        super(RequestLog.REQUEST_LOG, com.rongxingyn.xyf.domain.tables.pojos.RequestLog.class);
    }

    /**
     * Create a new RequestLogDao with an attached configuration
     */
    @Autowired
    public RequestLogDao(Configuration configuration) {
        super(RequestLog.REQUEST_LOG, com.rongxingyn.xyf.domain.tables.pojos.RequestLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.rongxingyn.xyf.domain.tables.pojos.RequestLog object) {
        return object.getLogId();
    }

    /**
     * Fetch records that have <code>log_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.RequestLog> fetchByLogId(String... values) {
        return fetch(RequestLog.REQUEST_LOG.LOG_ID, values);
    }

    /**
     * Fetch a unique record that has <code>log_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.RequestLog fetchOneByLogId(String value) {
        return fetchOne(RequestLog.REQUEST_LOG.LOG_ID, value);
    }

    /**
     * Fetch records that have <code>request_url IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.RequestLog> fetchByRequestUrl(String... values) {
        return fetch(RequestLog.REQUEST_LOG.REQUEST_URL, values);
    }

    /**
     * Fetch records that have <code>request_param IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.RequestLog> fetchByRequestParam(String... values) {
        return fetch(RequestLog.REQUEST_LOG.REQUEST_PARAM, values);
    }

    /**
     * Fetch records that have <code>result IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.RequestLog> fetchByResult(String... values) {
        return fetch(RequestLog.REQUEST_LOG.RESULT, values);
    }

    /**
     * Fetch records that have <code>channel_name IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.RequestLog> fetchByChannelName(String... values) {
        return fetch(RequestLog.REQUEST_LOG.CHANNEL_NAME, values);
    }

    /**
     * Fetch records that have <code>request_date IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.RequestLog> fetchByRequestDate(Timestamp... values) {
        return fetch(RequestLog.REQUEST_LOG.REQUEST_DATE, values);
    }
}
