/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.ShopInfo;
import com.rongxingyn.xyf.domain.tables.records.ShopInfoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ShopInfoDao extends DAOImpl<ShopInfoRecord, com.rongxingyn.xyf.domain.tables.pojos.ShopInfo, Integer> {

    /**
     * Create a new ShopInfoDao without any configuration
     */
    public ShopInfoDao() {
        super(ShopInfo.SHOP_INFO, com.rongxingyn.xyf.domain.tables.pojos.ShopInfo.class);
    }

    /**
     * Create a new ShopInfoDao with an attached configuration
     */
    @Autowired
    public ShopInfoDao(Configuration configuration) {
        super(ShopInfo.SHOP_INFO, com.rongxingyn.xyf.domain.tables.pojos.ShopInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.rongxingyn.xyf.domain.tables.pojos.ShopInfo object) {
        return object.getShopId();
    }

    /**
     * Fetch records that have <code>shop_id IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.ShopInfo> fetchByShopId(Integer... values) {
        return fetch(ShopInfo.SHOP_INFO.SHOP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>shop_id = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.ShopInfo fetchOneByShopId(Integer value) {
        return fetchOne(ShopInfo.SHOP_INFO.SHOP_ID, value);
    }

    /**
     * Fetch records that have <code>shop_name IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.ShopInfo> fetchByShopName(String... values) {
        return fetch(ShopInfo.SHOP_INFO.SHOP_NAME, values);
    }

    /**
     * Fetch records that have <code>shop_brief IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.ShopInfo> fetchByShopBrief(String... values) {
        return fetch(ShopInfo.SHOP_INFO.SHOP_BRIEF, values);
    }
}
