/*
 * This file is generated by jOOQ.
*/
package com.rongxingyn.xyf.domain.tables.daos;


import com.rongxingyn.xyf.domain.tables.TableTime;
import com.rongxingyn.xyf.domain.tables.records.TableTimeRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TableTimeDao extends DAOImpl<TableTimeRecord, com.rongxingyn.xyf.domain.tables.pojos.TableTime, String> {

    /**
     * Create a new TableTimeDao without any configuration
     */
    public TableTimeDao() {
        super(TableTime.TABLE_TIME, com.rongxingyn.xyf.domain.tables.pojos.TableTime.class);
    }

    /**
     * Create a new TableTimeDao with an attached configuration
     */
    @Autowired
    public TableTimeDao(Configuration configuration) {
        super(TableTime.TABLE_TIME, com.rongxingyn.xyf.domain.tables.pojos.TableTime.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.rongxingyn.xyf.domain.tables.pojos.TableTime object) {
        return object.getTableName();
    }

    /**
     * Fetch records that have <code>table_name IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.TableTime> fetchByTableName(String... values) {
        return fetch(TableTime.TABLE_TIME.TABLE_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>table_name = value</code>
     */
    public com.rongxingyn.xyf.domain.tables.pojos.TableTime fetchOneByTableName(String value) {
        return fetchOne(TableTime.TABLE_TIME.TABLE_NAME, value);
    }

    /**
     * Fetch records that have <code>deal_time IN (values)</code>
     */
    public List<com.rongxingyn.xyf.domain.tables.pojos.TableTime> fetchByDealTime(Timestamp... values) {
        return fetch(TableTime.TABLE_TIME.DEAL_TIME, values);
    }
}
